### ISSUE TITLE
Fix Grafana bootstrapping process

### ISSUE THREAD

**Issue by kirillmakhonin** [legion-platform/legion#294]

**Comment by kirillmakhonin** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/legion_bootstrap_grafana", line 27, in <module>
    from legion_test.grafana import GrafanaClient
  File "/usr/local/lib/python3.4/dist-packages/legion_test/grafana.py", line 23, in <module>
    from legion_test.robot.dex_client import get_session_cookies
  File "/usr/local/lib/python3.4/dist-packages/legion_test/robot/__init__.py", line 4, in <module>
    from .grafana import Grafana
  File "/usr/local/lib/python3.4/dist-packages/legion_test/robot/grafana.py", line 19, in <module>
    from legion_test.grafana import GrafanaClient
ImportError: cannot import name 'GrafanaClient'
```

**Comment by akharlamov** [comment]
Closing issue as the PR has been merged.
