### ISSUE TITLE
Legionctl undeploy/scale commands with '*' parameter does not work

### ISSUE THREAD

**Issue by ablatov** [legion-platform/legion#345]
**Preconditions to all error commands (deploy two models with diff versions but the same id):**
1.) legionctl deploy nexus-local.cc.epm.kharlamov.biz:443/legion/test-bare-model-api-model-1:0.7.0-180816072015.1184.20be2da --edi https://edi-company-a.legion-demo.epm.kharlamov.biz --user admin --password admin
2.) legionctl deploy nexus-local.cc.epm.kharlamov.biz:443/legion/test-bare-model-api-model-2:0.7.0-180816072015.1184.20be2da --edi https://edi-company-a.legion-demo.epm.kharlamov.biz --user admin --password admin

**Undeploy:**
1.) legionctl undeploy '*' --ignore-not-found --edi https://edi-company-a.legion-demo.epm.kharlamov.biz --user admin --password admin
**Output:**
2018-08-16 14:43:46,228 - ERROR - Founded more then one deployment
Traceback (most recent call last):
  File "/home/alex/PycharmProjects/legion/legion/bin/legionctl", line 139, in <module>
    args.func(args)
  File "/home/alex/PycharmProjects/legion/legion/legion/edi/deploy.py", line 178, in undeploy_kubernetes
    raise Exception('Founded more then one deployment')
Exception: Founded more then one deployment

2.) legionctl undeploy demo-abc-model --model-version '*' --ignore-not-found --edi https://edi-company-a.legion-demo.epm.kharlamov.biz --user admin --password admin2018-08-16 14:48:51,897 - ERROR - Founded more then one deployment
**Output:**
Traceback (most recent call last):
  File "/home/alex/PycharmProjects/legion/legion/bin/legionctl", line 139, in <module>
    args.func(args)
  File "/home/alex/PycharmProjects/legion/legion/legion/edi/deploy.py", line 178, in undeploy_kubernetes
    raise Exception('Founded more then one deployment')
Exception: Founded more then one deployment

**Scale**
1.) legionctl scale '*' 2 --edi https://edi-company-a.legion-demo.epm.kharlamov.biz --user admin --password admin
**Output:**
2018-08-16 14:57:16,924 - ERROR - Got error from server: 'Please specify version of model'
Traceback (most recent call last):
  File "/home/alex/PycharmProjects/legion/legion/bin/legionctl", line 139, in <module>
    args.func(args)
  File "/home/alex/PycharmProjects/legion/legion/legion/edi/deploy.py", line 211, in scale_kubernetes
    edi_client.scale(args.model_id, args.scale, args.model_version)
  File "/home/alex/PycharmProjects/legion/legion/legion/external/edi.py", line 190, in scale
    return self._query(legion.edi.server.EDI_SCALE, action='POST', payload=payload)['status']
  File "/home/alex/PycharmProjects/legion/legion/legion/external/edi.py", line 95, in _query
    raise Exception('Got error from server: {!r}'.format(exception))
Exception: Got error from server: 'Please specify version of model'

**Comment by ablatov** [comment]
Done in #553
