### ISSUE TITLE
Network layer of k8s is not stable need to update it

### ISSUE THREAD

**Issue by ablatov** [legion-platform/legion#627]
We face with network stability problems on our current network k8s version during multiple and fast operations with our test models like"scale, deploy, undeploy" legionctl commands.
Because of that, we have failed tests sometimes 
```
2018-11-26 02:19:14,100 - ERROR - Time out: operation has not been confirmed
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/bin/legionctl", line 178, in <module>
    args.func(args)
  File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/legion/edi/deploy.py", line 282, in scale_kubernetes
    lambda affected_deployments_status: check_all_scaled(affected_deployments_status,
  File "/var/lib/jenkins/workspace/Deploy_Legion_Release/legion/legion/edi/deploy.py", line 207, in wait_operation_finish
    raise Exception('Time out: operation has not been confirmed')
Exception: Time out: operation has not been confirmed
```

**Comment by alexander-semenets** [comment]
fixed  in [#714] calico cni #792
